add role and rolebinding defs
fiaas/k8s pull request #96
Opened 2021-09-13 07:46 UTC by j18e

2021-09-13 08:06 UTC, birgirst submitted a review, later dismissed

2021-09-13 14:51 UTC, oyvindio requested changes
I've left some comments inline. I think it would also be really nice to have some simple get/update/delete etc. tests for these models, similar to those that exist for other model classes here https://github.com/fiaas/k8s/tree/master/tests/k8s

2021-09-13 14:51 UTC, oyvindio commented on k8s/models/role.py
> +    nonResourceUrls = ListField(str)
Should this be `nonResourceURLs`?

2021-09-13 14:51 UTC, oyvindio commented on k8s/models/role_binding.py
> +    roleRef = Field(str)
As far as I can see, RoleRef doesn't have a `roleRef` field, but it has a `name` field which should probably be added here

2021-09-13 14:51 UTC, oyvindio commented on k8s/models/role_binding.py
> +    namespace = Field(str)
As above; string fields should use six.text_type

2021-09-15 07:48 UTC, j18e reviewed
these have been done

2021-09-15 07:59 UTC, oyvindio approved these changes
Thanks for adding tests! This looks good 👍

2021-09-15 09:03 UTC, merged